imports:
    - { resource: parameters.yml }
    - { resource: parametersAdmission.yml }
    - { resource: vars.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        dir_staff: '/uploads/staff'
        dir_students: '/uploads/students'
        dir_parents: '/uploads/parents'
        dir_other: '/uploads/others'
# Parámetros globales del contenedor de dependencias
parameters:
    photo.staff: %kernel.root_dir%/../web/photos/staff/
    photo.students: %kernel.root_dir%/../web/photos/students/
    photo.parents: %kernel.root_dir%/../web/photos/parents/
    photo.others: %kernel.root_dir%/../web/photos/others/
    photo.targetPath: %kernel.root_dir%/../web/photos/
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        jpegoptim:
            bin: ruta/a/jpegoptim
# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text 
            admission:
                driver:   %database_driver2%
                host:     %database_host2%
                port:     %database_port2%
                dbname:   %database_name2%
                user:     %database_user2%
                password: %database_password2%
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text 
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    ABCIsystemBundle: ~
                    #ABCBookingBundle: ~
            admission:
                connection:       admission
                mappings:
                    ABCAdmissionBundle: ~
    #orm:
    #    auto_generate_proxy_classes: %kernel.debug%
    #    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        filtration: KnpPaginatorBundle:Pagination:filtration.html.twig # sort link template
