parameters:
    database_driver2: pdo_mysql
    database_host2: 127.0.0.1
    database_port2: null
    database_name2: admissions
    database_user2: admissions
    database_password2: trali20ausa
    mailer_transport2: smtp
    mailer_host2: 127.0.0.1
    mailer_user2: null
    mailer_password2: null
    locale2: en
    secret2: 50cf7f4e67a3670b8a76516383c95a80600c60ed
