parameters:
#    abc_isystem.example.class: ABC\IsystemBundle\Example

services:
#    abc_isystem.example:
#        class: %abc_isystem.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    imageResize:
        class: ABC\IsystemBundle\Service\imageResizeService
        arguments: 
            entityManagerMy: "@doctrine.orm.default_entity_manager"
    imageCrop:
        class: ABC\IsystemBundle\Service\imageCropService
        arguments: 
            entityManagerMy: "@doctrine.orm.default_entity_manager"           