parameters:
#    booking.example.class: ABC\BookingBundle\Example

services:
#    booking.example:
#        class: %booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
